CREATE DATABASE vls_database;
use vls_database ;


SHOW TABLEs;

CREATE TABLE COURSES (
    COURSE_ID VARCHAR(10) PRIMARY KEY AUTO_INCREMENT,
    COURSE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    TRAINER VARCHAR(50) NOT NULL,
    PRICE INT NOT NULL
);

DESC admin;
select * from learners;


